USE [master]
GO

/****** Object:  Database [New3S]    Script Date: 5/16/2019 12:34:17 PM ******/
CREATE DATABASE [New3S]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'New3S', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.HONG\MSSQL\DATA\New3S.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'New3S_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.HONG\MSSQL\DATA\New3S_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [New3S] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [New3S].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [New3S] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [New3S] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [New3S] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [New3S] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [New3S] SET ARITHABORT OFF 
GO

ALTER DATABASE [New3S] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [New3S] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [New3S] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [New3S] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [New3S] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [New3S] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [New3S] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [New3S] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [New3S] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [New3S] SET  DISABLE_BROKER 
GO

ALTER DATABASE [New3S] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [New3S] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [New3S] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [New3S] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [New3S] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [New3S] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [New3S] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [New3S] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [New3S] SET  MULTI_USER 
GO

ALTER DATABASE [New3S] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [New3S] SET DB_CHAINING OFF 
GO

ALTER DATABASE [New3S] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [New3S] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [New3S] SET  READ_WRITE 
GO

